# -*- coding: utf-8 -*-
"""FIBONACCI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DuKJQNMyWoVaSvXq8dgizJaj63UfhLBs

LEC05_FIBONACCI
"""

n = 10
a = 0
b = 1

for i in range(n):
    print(a, end=" ")
    next = a + b
    a = b
    b = next